#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#include <stdio.h>

#define STRINGIFY_INNER(value) #value
#define STRINGIFY(value) STRINGIFY_INNER(value)

static const char* const kRequiredSymbols[] = {
#define PB_INS_QUERY0(return_kind, c_symbol, pin_symbol, api_id) STRINGIFY(c_symbol),
#define PB_INS_QUERY1(return_kind, argument_kind, c_symbol, pin_symbol, api_id) STRINGIFY(c_symbol),
#include "pinbridge/generated/ins_inspection_queries.inc"
#undef PB_INS_QUERY1
#undef PB_INS_QUERY0
#define PB_HANDLE_QUERY0(input_kind, return_kind, c_symbol, pin_symbol, api_id) STRINGIFY(c_symbol),
#define PB_HANDLE_QUERY1(input_kind, return_kind, argument_kind, c_symbol, pin_symbol, api_id) STRINGIFY(c_symbol),
#include "pinbridge/generated/structure_queries.inc"
#undef PB_HANDLE_QUERY1
#undef PB_HANDLE_QUERY0
#define PB_REG_QUERY0(return_kind, c_symbol, pin_symbol, api_id) STRINGIFY(c_symbol),
#define PB_REG_QUERY1(return_kind, argument_kind, c_symbol, pin_symbol, api_id) STRINGIFY(c_symbol),
#include "pinbridge/generated/reg_queries.inc"
#undef PB_REG_QUERY1
#undef PB_REG_QUERY0
    "pb_trace_add_instrument_function",
    "pb_rtn_add_instrument_function",
    "pb_img_add_instrument_function",
    "pb_app_img_head",
    "pb_app_img_tail",
    "pb_img_add_unload_function",
    "pb_img_close",
    "pb_img_find_by_address",
    "pb_img_find_by_id",
    "pb_img_invalid",
    "pb_img_name",
    "pb_img_open",
    "pb_rtn_close",
    "pb_rtn_create_at",
    "pb_rtn_open",
    "pb_rtn_replace",
    "pb_rtn_replace_probed",
    "pb_rtn_replace_probed_ex",
    "pb_iarg_list_alloc",
    "pb_iarg_list_add",
    "pb_iarg_list_free",
    "pb_rtn_insert_call",
    "pb_rtn_insert_call_probed",
    "pb_rtn_insert_call_probed_ex",
    "pb_rtn_replace_signature",
    "pb_rtn_replace_signature_probed",
    "pb_rtn_replace_signature_probed_ex",
    "pb_regset_add_all",
    "pb_regset_clear",
    "pb_regset_contains",
    "pb_regset_insert",
    "pb_regset_pop_count",
    "pb_regset_is_empty",
    "pb_regset_pop_next",
    "pb_regset_remove",
    "pb_regset_first_reg",
    "pb_regset_last_reg",
    "pb_regset_string_short",
    "pb_pin_get_context_regval",
    "pb_pin_save_context",
    "pb_pin_set_context_reg",
    "pb_pin_set_context_regval",
    "pb_pin_execute_at",
    "pb_pin_check_read_access",
    "pb_pin_check_write_access",
    "pb_pin_is_attaching",
    "pb_pin_is_probe_mode",
    "pb_pin_is_safe_for_probed_insertion",
    "pb_pin_tool_full_path",
    "pb_pin_get_source_location",
    "pb_pin_add_application_start_function",
    "pb_pin_add_prepare_for_fini_function",
    "pb_pin_add_fini_function",
    "pb_pin_add_thread_start_function",
    "pb_pin_add_thread_fini_function",
    "pb_pin_add_context_change_function",
    "pb_pin_add_xed_decode_callback_function",
    "pb_xed_decoded_inst_set_features",
    "pb_pin_add_fetch_function",
    "pb_pin_fetch_code",
    "pb_pin_add_internal_exception_handler",
    "pb_pin_try_end",
    "pb_pin_try_start",
    "pb_pin_add_memory_address_trans_function",
    "pb_pin_get_memory_address_trans_function",
    "pb_pin_add_out_of_memory_function",
    "pb_pin_add_follow_child_process_function",
    "pb_child_process_get_command_line_count",
    "pb_child_process_get_command_line_argument",
    "pb_child_process_get_id",
    "pb_child_process_set_pin_command_line",
    "pb_pin_insert_call_probed",
    "pb_pin_safe_copy_ex",
    "pb_pin_add_detach_function",
    "pb_pin_add_detach_function_probed",
    "pb_pin_detach",
    "pb_pin_detach_probed",
    "pb_pin_attach_probed",
    "pb_pin_init_symbols",
    "pb_pin_init_symbols_alt",
    "pb_pin_lock_client",
    "pb_pin_unlock_client",
    "pb_pin_set_smc_support",
    "pb_pin_start_program_probed",
    "pb_pin_create_default_configuration_info",
    "pb_pin_start_program_configured",
    "pb_pin_remove_fini_functions",
    "pb_pin_remove_instrumentation",
    "pb_pin_remove_instrumentation_in_range",
    "pb_sec_data",
    "pb_sec_invalid",
    "pb_sec_name",
    "pb_pin_claim_tool_register",
    "pb_reg_convert_x87_abridged_tag_to_full",
    "pb_reg_string_short",
    "pb_reg_prefix_increment",
    "pb_reg_postfix_increment",
    "pb_reg_postfix_decrement",
    "pb_callback_get_execution_priority_deprecated",
    "pb_callback_set_execution_priority_deprecated",
    "pb_img_entry_deprecated",
    "pb_img_create_at",
    "pb_img_replay_image_load",
    "pb_pin_replay_context_change",
    "pb_round_down_addr",
    "pb_round_down_u64",
    "pb_round_up_addr",
    "pb_round_up_u64",
    "pb_mem_page_range_addr",
    "pb_mem_page_range_pointer",
    "pb_decstr_i16",
    "pb_decstr_i32",
    "pb_decstr_i64",
    "pb_decstr_u16",
    "pb_decstr_u32",
    "pb_decstr_u64",
    "pb_fltstr",
    "pb_hexstr_i16",
    "pb_hexstr_i32",
    "pb_hexstr_i64",
    "pb_hexstr_u16",
    "pb_hexstr_u32",
    "pb_hexstr_u64",
    "pb_hexstr_pointer",
    "pb_hexstr_const_pointer",
    "pb_read_line",
    "pb_ptr_at_offset_typed",
    "pb_const_ptr_at_offset_typed",
    "pb_knob_check_all", "pb_knob_compare",
    "pb_knob_find_enabled", "pb_knob_find_family", "pb_knob_find",
    "pb_knob_slow_asserts", "pb_knob_count", "pb_knob_set_by_user",
    "pb_knob_summary", "pb_knob_long_all", "pb_knob_turn_on_set_by_user",
    "pb_img_get_loader_info", "pb_img_set_loader_info",
    "pb_pin_add_breakpoint_handler", "pb_pin_add_debug_interpreter",
    "pb_pin_add_debugger_register_emulator", "pb_pin_application_breakpoint",
    "pb_pin_change_pending_tool_breakpoint", "pb_pin_get_debug_connection_info",
    "pb_pin_get_debug_status", "pb_pin_get_debugger_type",
    "pb_pin_get_pending_tool_breakpoint", "pb_pin_intercept_debugging_event",
    "pb_pin_remove_breakpoint_handler", "pb_pin_remove_debug_interpreter",
    "pb_pin_reset_breakpoint_at", "pb_pin_set_debug_mode",
    "pb_pin_wait_for_debugger",
    "pb_exception_info_release",
    "pb_pin_count_windows_exception_arguments", "pb_pin_exception_to_string",
    "pb_pin_get_exception_address", "pb_pin_get_exception_class",
    "pb_pin_get_exception_code", "pb_pin_get_faulty_access_address",
    "pb_pin_get_faulty_access_type", "pb_pin_get_fp_error_set",
    "pb_pin_get_windows_exception_argument", "pb_pin_get_windows_exception_code",
    "pb_pin_init_access_fault_info", "pb_pin_init_exception_info",
    "pb_pin_init_windows_exception_info", "pb_pin_raise_exception",
    "pb_pin_set_exception_address",
    "pb_pin_init_lock", "pb_pin_lock_destroy", "pb_pin_get_lock",
    "pb_pin_release_lock", "pb_pin_mutex_init", "pb_pin_mutex_fini",
    "pb_pin_mutex_lock", "pb_pin_mutex_try_lock", "pb_pin_mutex_unlock",
    "pb_pin_rwmutex_init", "pb_pin_rwmutex_fini",
    "pb_pin_rwmutex_read_lock", "pb_pin_rwmutex_try_read_lock",
    "pb_pin_rwmutex_try_write_lock", "pb_pin_rwmutex_unlock",
    "pb_pin_rwmutex_write_lock", "pb_pin_semaphore_init",
    "pb_pin_semaphore_fini", "pb_pin_semaphore_clear",
    "pb_pin_semaphore_is_set", "pb_pin_semaphore_set",
    "pb_pin_semaphore_timed_wait", "pb_pin_semaphore_wait",
    "pb_assert_string", "pb_break_me", "pb_milliseconds_elapsed",
    "pb_pin_create_thread_data_key", "pb_pin_delete_thread_data_key",
    "pb_pin_exit_thread", "pb_pin_get_parent_tid",
    "pb_pin_get_stopped_thread_context", "pb_pin_get_stopped_thread_count",
    "pb_pin_get_stopped_thread_id", "pb_pin_get_stopped_thread_writeable_context",
    "pb_pin_get_thread_data", "pb_pin_get_tid", "pb_pin_is_application_thread",
    "pb_pin_is_thread_stopped_in_debugger", "pb_pin_resume_application_threads",
    "pb_pin_set_thread_data", "pb_pin_sleep", "pb_pin_spawn_application_thread",
    "pb_pin_spawn_internal_thread", "pb_pin_stop_application_threads",
    "pb_pin_thread_id", "pb_pin_thread_uid", "pb_pin_wait_for_thread_termination",
    "pb_pin_yield",
    "pb_rtn_find_by_address",
    "pb_rtn_find_by_name",
    "pb_rtn_find_name_by_address",
    "pb_rtn_funptr",
    "pb_rtn_invalid",
    "pb_rtn_name",
};

int main(int argc, char** argv)
{
    size_t index;
    HMODULE module;
    if (argc != 2)
        return 1;
    module = LoadLibraryA(argv[1]);
    if (!module)
        return 2;
    for (index = 0; index < sizeof(kRequiredSymbols) / sizeof(kRequiredSymbols[0]); ++index)
    {
        if (!GetProcAddress(module, kRequiredSymbols[index]))
        {
            fprintf(stderr, "missing generated export: %s\n", kRequiredSymbols[index]);
            return 3;
        }
    }
    FreeLibrary(module);
    return 0;
}
