#include "pin.H"
#include "exception_backend.h"
#include <cstdlib>
#include <cstring>
#include <string>
namespace{EXCEPTION_INFO*P(PbExceptionInfoHandle h){return reinterpret_cast<EXCEPTION_INFO*>(h);}PbExceptionInfoHandle H(EXCEPTION_INFO*p){return reinterpret_cast<PbExceptionInfoHandle>(p);}PbStatus Copy(const std::string&s,char*b,uint64_t c,uint64_t*r){*r=s.size()+1;if(!b||c<*r)return PB_ERR_BUFFER_TOO_SMALL;std::memcpy(b,s.c_str(),static_cast<size_t>(*r));return PB_OK;}EXCEPTION_INFO*New(){return static_cast<EXCEPTION_INFO*>(std::malloc(sizeof(EXCEPTION_INFO)));}}
static_assert(PB_EXCEPTCLASS_OS==EXCEPTCLASS_OS,"exception class drift");static_assert(PB_EXCEPTCODE_RECEIVED_AMBIGUOUS_SIMD==EXCEPTCODE_RECEIVED_AMBIGUOUS_SIMD,"exception code drift");static_assert(PB_FAULTY_ACCESS_EXECUTE==FAULTY_ACCESS_EXECUTE,"access type drift");static_assert(PB_FPERROR_X87_STACK_ERROR==FPERROR_X87_STACK_ERROR,"FP error drift");static_assert(PB_MAX_WINDOWS_EXCEPTION_ARGS==MAX_WINDOWS_EXCEPTION_ARGS,"argument count drift");
PbStatus PbBackendExceptionRelease(PbExceptionInfoHandle h){std::free(P(h));return PB_OK;} PbStatus PbBackendExceptionCount(PbExceptionInfoHandle h,uint32_t*o){*o=PIN_CountWindowsExceptionArguments(P(h));return PB_OK;} PbStatus PbBackendExceptionString(PbExceptionInfoHandle h,char*b,uint64_t c,uint64_t*r){return Copy(PIN_ExceptionToString(P(h)),b,c,r);} PbStatus PbBackendExceptionAddress(PbExceptionInfoHandle h,uint64_t*o){*o=PIN_GetExceptionAddress(P(h));return PB_OK;} PbStatus PbBackendExceptionClass(PbExceptionCode c,PbExceptionClass*o){*o=PIN_GetExceptionClass(static_cast<EXCEPTION_CODE>(c));return PB_OK;} PbStatus PbBackendExceptionCode(PbExceptionInfoHandle h,PbExceptionCode*o){*o=PIN_GetExceptionCode(P(h));return PB_OK;}
PbStatus PbBackendExceptionFaultAddress(PbExceptionInfoHandle h,uint64_t*a,uint8_t*k){EXCEPTION_INFO*p=P(h);*a=0;*k=0;if(PIN_GetExceptionClass(PIN_GetExceptionCode(p))!=EXCEPTCLASS_ACCESS_FAULT)return PB_ERR_INVALID_ARGUMENT;ADDRINT x=0;*k=PIN_GetFaultyAccessAddress(p,&x)?1:0;*a=x;return PB_OK;} PbStatus PbBackendExceptionFaultType(PbExceptionInfoHandle h,PbFaultyAccessType*o){EXCEPTION_INFO*p=P(h);*o=PB_FAULTY_ACCESS_TYPE_UNKNOWN;if(PIN_GetExceptionClass(PIN_GetExceptionCode(p))!=EXCEPTCLASS_ACCESS_FAULT)return PB_ERR_INVALID_ARGUMENT;*o=PIN_GetFaultyAccessType(p);return PB_OK;} PbStatus PbBackendExceptionFpErrors(PbExceptionInfoHandle h,uint32_t*o){*o=PIN_GetFpErrorSet(P(h));return PB_OK;} PbStatus PbBackendExceptionWindowsArg(PbExceptionInfoHandle h,uint32_t i,uint64_t*o){if(i>=PIN_CountWindowsExceptionArguments(P(h)))return PB_ERR_INVALID_ARGUMENT;*o=PIN_GetWindowsExceptionArgument(P(h),i);return PB_OK;} PbStatus PbBackendExceptionWindowsCode(PbExceptionInfoHandle h,uint32_t*o){*o=PIN_GetWindowsExceptionCode(P(h));return PB_OK;}
PbStatus PbBackendExceptionInitAccess(PbExceptionCode c,uint64_t e,uint64_t a,PbFaultyAccessType t,PbExceptionInfoHandle*o){EXCEPTION_INFO*p=New();if(!p)return PB_ERR_OUT_OF_MEMORY;PIN_InitAccessFaultInfo(p,static_cast<EXCEPTION_CODE>(c),e,a,static_cast<FAULTY_ACCESS_TYPE>(t));*o=H(p);return PB_OK;} PbStatus PbBackendExceptionInit(PbExceptionCode c,uint64_t a,PbExceptionInfoHandle*o){EXCEPTION_INFO*p=New();if(!p)return PB_ERR_OUT_OF_MEMORY;PIN_InitExceptionInfo(p,static_cast<EXCEPTION_CODE>(c),a);*o=H(p);return PB_OK;} PbStatus PbBackendExceptionInitWindows(uint32_t c,uint64_t a,const uint64_t*v,uint32_t n,PbExceptionInfoHandle*o){EXCEPTION_INFO*p=New();if(!p)return PB_ERR_OUT_OF_MEMORY;ADDRINT args[PB_MAX_WINDOWS_EXCEPTION_ARGS]={};for(uint32_t i=0;i<n;i++)args[i]=v[i];PIN_InitWindowsExceptionInfo(p,c,a,n,args);*o=H(p);return PB_OK;} PbStatus PbBackendExceptionRaise(PbConstContextHandle c,PbThreadId t,PbExceptionInfoHandle h){PIN_RaiseException(reinterpret_cast<const CONTEXT*>(c),t,P(h));return PB_OK;} PbStatus PbBackendExceptionSetAddress(PbExceptionInfoHandle h,uint64_t a){PIN_SetExceptionAddress(P(h),a);return PB_OK;}
